### ISSUE TITLE
UUID and NEXMO_CALL_UUID constants undefined

### ISSUE THREAD

**Issue by timcraft** [Nexmo/nexmo-ruby-code-snippets#56]
Some of the voice snippets reference a UUID constant which isn't defined:

* voice/play-dtmf-into-call.rb
* voice/mute-a-call.rb
* voice/play-text-to-speech-into-a-call.rb
* voice/earmuff-a-call.rb
* voice/transfer-a-call.rb
* voice/play-audio-stream-into-call.rb

There's only voice/transfer-a-call-ncco.rb which defines the constant.

There's also voice/retrieve-info-for-a-call.rb which references NEXMO_CALL_UUID.

Easy to fix—would UUID or NEXMO_CALL_UUID be preferable for the env variable?

**Comment by benhayehudi** [comment]
Hi @timcraft,

The `transfer-a-call-ncco` is our newest snippet in this category, and its details were thoroughly reviewed, so I would use the `UUID` variable name.

Thanks,

Ben
